# Generated by Django 5.2.1 on 2025-06-27 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApoyoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la sección', max_length=200, verbose_name='Título')),
                ('texto', models.TextField(help_text='Contenido de texto de la sección', verbose_name='Texto')),
                ('imagen', models.ImageField(help_text='Imagen de la sección', upload_to='proyectos/apoyo_institucional/', verbose_name='Imagen')),
                ('texto_boton', models.CharField(default='Contactar', help_text='Texto que aparecerá en el botón de contacto', max_length=50, verbose_name='Texto del botón')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para mostrar esta sección', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proyectos - Apoyo Institucional',
                'verbose_name_plural': 'Proyectos - Apoyo Institucional',
            },
        ),
        migrations.CreateModel(
            name='BecasEscolares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de la sección', upload_to='proyectos/becas/', verbose_name='Imagen')),
                ('titulo', models.CharField(help_text='Título de la sección', max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(help_text='Subtítulo de la sección', max_length=300, verbose_name='Subtítulo')),
                ('texto', models.TextField(help_text='Contenido de texto de la sección', verbose_name='Texto')),
                ('texto_boton', models.CharField(default='Contactar', help_text='Texto que aparecerá en el botón de contacto', max_length=50, verbose_name='Texto del botón')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para mostrar esta sección', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proyectos - Becas Escolares',
                'verbose_name_plural': 'Proyectos - Becas Escolares',
            },
        ),
        migrations.CreateModel(
            name='ConvocatoriasDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la sección de documentos', max_length=200, verbose_name='Título')),
                ('texto', models.TextField(help_text='Texto descriptivo de la sección', verbose_name='Texto')),
                ('texto_boton', models.CharField(default='Leer', help_text='Texto que aparecerá en los botones de los documentos', max_length=50, verbose_name='Texto del botón')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para mostrar esta sección', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proyectos - Convocatorias y Documentos',
                'verbose_name_plural': 'Proyectos - Convocatorias y Documentos',
            },
        ),
        migrations.CreateModel(
            name='ProgramasEducativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la sección de tarjetas', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(help_text='Breve descripción de la sección', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para mostrar esta sección', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proyectos - Programas Educativos',
                'verbose_name_plural': 'Proyectos - Programas Educativos',
            },
        ),
        migrations.CreateModel(
            name='ProyectosHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título principal de la sección', max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(help_text='Subtítulo descriptivo', max_length=300, verbose_name='Subtítulo')),
                ('contenido', models.TextField(help_text='Contenido principal de la sección', verbose_name='Contenido')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para mostrar esta sección', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proyectos - Sección Hero',
                'verbose_name_plural': 'Proyectos - Sección Hero',
            },
        ),
        migrations.CreateModel(
            name='DocumentoConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen representativa del documento', upload_to='proyectos/documentos/', verbose_name='Imagen')),
                ('titulo', models.CharField(help_text='Título del documento', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del documento', verbose_name='Descripción')),
                ('archivo_pdf', models.FileField(help_text='Archivo PDF del documento', upload_to='proyectos/convocatorias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Archivo PDF')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición del documento', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para mostrar este documento', verbose_name='Activo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_convocatoria', to='projects.convocatoriasdocumentos', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Documento de Convocatoria',
                'verbose_name_plural': 'Documentos de Convocatorias',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen principal de la tarjeta', upload_to='proyectos/tarjetas/', verbose_name='Imagen')),
                ('subtitulo', models.CharField(help_text='Subtítulo de la tarjeta', max_length=150, verbose_name='Subtítulo')),
                ('titulo', models.CharField(help_text='Título principal de la tarjeta', max_length=200, verbose_name='Título')),
                ('contenido_vinetas', models.TextField(help_text='Escribe cada viñeta en una línea nueva. Cada línea será mostrada como un elemento de lista con bullet.', verbose_name='Contenido (viñetas)')),
                ('texto_boton', models.CharField(default='Ver más', help_text='Texto que aparecerá en el botón de acción', max_length=50, verbose_name='Texto del botón')),
                ('titulo_trasero', models.CharField(help_text='Título que aparece cuando se voltea la tarjeta', max_length=200, verbose_name='Título (lado trasero)')),
                ('contenido_trasero_vinetas', models.TextField(help_text='Contenido del lado trasero. Escribe cada viñeta en una línea nueva.', verbose_name='Contenido trasero (viñetas)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición de la tarjeta', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para mostrar esta tarjeta', verbose_name='Activo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_programa', to='projects.programaseducativos', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Tarjeta de Programa Educativo',
                'verbose_name_plural': 'Tarjetas de Programas Educativos',
                'ordering': ['orden'],
            },
        ),
    ]
