# Generated by Django 5.2.1 on 2025-07-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='becasescolares',
            name='contenido_vinetas',
            field=models.TextField(default='', help_text='Contenido de los requisitos de beca. Escribe cada viñeta en una línea nueva.', verbose_name='Contenido (viñetas)'),
            preserve_default=False,
        ),
    ]
