# Generated by Django 5.2.1 on 2025-06-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donor_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_phone',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='phone',
            field=models.CharField(default=5512345678, max_length=12),
            preserve_default=False,
        ),
    ]
