# Generated by Django 5.2.1 on 2025-06-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='Logo de Donations', max_length=100),
        ),
    ]
