# Generated by Django 5.2.1 on 2025-06-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_siteconfiguration_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSuccessPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la página')),
                ('title', models.CharField(default='¡Donación Exitosa!', max_length=200, verbose_name='Título Principal')),
                ('subtitle', models.TextField(default='Tu generosa contribución ha sido procesada correctamente. Gracias por apoyar nuestra causa.', verbose_name='Subtítulo Principal')),
                ('confirmation_title', models.CharField(default='Tu apoyo hace la diferencia', max_length=200, verbose_name='Título de la Confirmación')),
                ('confirmation_text', models.TextField(default='Hemos recibido tu donación...', verbose_name='Texto de la Confirmación')),
                ('impact_title', models.CharField(default='Tu donación ayudará a:', max_length=200, verbose_name='Título del Impacto')),
                ('impact_bullet_1', models.CharField(default='Brindar apoyo directo a familias necesitadas', max_length=255, verbose_name='Impacto punto 1')),
                ('impact_bullet_2', models.CharField(default='Desarrollar programas educativos en comunidades', max_length=255, verbose_name='Impacto punto 2')),
                ('impact_bullet_3', models.CharField(default='Fortalecer nuestra misión de crecimiento social', max_length=255, verbose_name='Impacto punto 3')),
                ('email_title', models.CharField(default='Recibo por Email', max_length=200, verbose_name='Título Email')),
                ('email_text', models.CharField(default='Te enviaremos tu recibo fiscal en los próximos minutos', max_length=255, verbose_name='Texto Email')),
                ('help_title', models.CharField(default='¿Necesitas ayuda?', max_length=200, verbose_name='Título Ayuda')),
                ('help_text', models.CharField(default='Contáctanos si tienes alguna pregunta sobre tu donación', max_length=255, verbose_name='Texto Ayuda')),
                ('share_title', models.CharField(default='¡Comparte nuestra causa!', max_length=200, verbose_name='Título Compartir')),
                ('share_text', models.TextField(default='Ayúdanos a llegar a más personas compartiendo nuestra misión en redes sociales.', verbose_name='Texto Compartir')),
                ('share_text_facebook', models.CharField(default='¡Acabo de hacer una donación para apoyar a Crecer México! Únete a esta noble causa.', max_length=255, verbose_name='Texto para compartir en Facebook')),
                ('share_text_twitter', models.CharField(default='¡Acabo de hacer una donación para apoyar a Crecer México! Únete a esta noble causa.', max_length=255, verbose_name='Texto para compartir en Twitter')),
                ('share_text_whatsapp', models.CharField(default='¡Acabo de hacer una donación para apoyar a Crecer México! Únete a esta noble causa.', max_length=255, verbose_name='Texto para compartir en WhatsApp')),
            ],
            options={
                'verbose_name': 'Página de Donación Exitosa',
                'verbose_name_plural': 'Página de Donación Exitosa',
            },
        ),
    ]
