# Generated by Django 5.2.1 on 2025-06-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donationsuccesspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationsuccesspage',
            old_name='impact_bullet_1',
            new_name='impact_text_1',
        ),
    ]
