# Generated by Django 5.2.1 on 2025-06-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_rename_impact_bullet_1_donationsuccesspage_impact_text_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationsuccesspage',
            old_name='impact_text_1',
            new_name='impact_bullet_1',
        ),
    ]
