# Generated by Django 5.2.1 on 2025-06-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_rename_impact_text_1_donationsuccesspage_impact_bullet_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_subtitle',
            field=models.CharField(default='Tu apoyo hace la diferencia. Cada contribución nos ayuda a seguir adelante con nuestra misión', max_length=200, verbose_name='Subtítulo de Donaciones '),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='main_title',
            field=models.CharField(default='Haz una Donación', max_length=200, verbose_name='Titulo de Donaciones '),
        ),
    ]
