# Generated by Django 5.2.1 on 2025-06-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_siteconfiguration_main_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='suggested_amount_1',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='suggested_amount_2',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='suggested_amount_3',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='suggested_label',
            field=models.CharField(default='Montos sugeridos:', max_length=100, verbose_name='Sección de montos sugeridos'),
        ),
    ]
