# Generated by Django 5.2.1 on 2025-06-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_siteconfiguration_suggested_amount_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationsuccesspage',
            options={'verbose_name': 'Página de DonaciónES Exitosa', 'verbose_name_plural': 'Página de Donación Exitosa'},
        ),
    ]
