# Generated by Django 5.2.1 on 2025-06-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_alter_donationsuccesspage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationsuccesspage',
            options={'verbose_name': 'Página de Donación Exitosa', 'verbose_name_plural': 'Página de Donación Exitosa'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Página para Configurar Donaciones'},
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='Logo de Donaciones', max_length=100),
        ),
    ]
