# Generated by Django 5.2.1 on 2025-06-13 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_alter_donationsuccesspage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationsuccesspage',
            options={'verbose_name': 'Configuración de  Donación Exitosa', 'verbose_name_plural': 'Página de Donación Exitosa'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Configuración de Donaciones'},
        ),
    ]
