# Generated by Django 5.2.1 on 2025-06-13 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_alter_donationsuccesspage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationsuccesspage',
            options={'verbose_name': 'Configuración de  Donación Exitosa'},
        ),
    ]
