# Generated by Django 5.2.1 on 2025-06-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_alter_donationsuccesspage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='security_title',
            field=models.CharField(default='Donación Segura', max_length=100, verbose_name='Titulo de recuadro bajo:'),
        ),
    ]
