# Generated by Django 5.2.1 on 2025-06-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_siteconfiguration_security_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='security_text',
            field=models.CharField(default='Todas las transacciones están protegidas con encriptación de alta seguridad.Tu información personal y financiera está completamente segura', max_length=100, verbose_name='Texto de recuadro bajo:'),
        ),
    ]
