# Generated by Django 5.2.1 on 2025-06-05 16:47

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCollage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo de la imagen', max_length=100)),
                ('imagen', models.ImageField(help_text='Imagen para el collage', upload_to='quienes_somos/collages/')),
                ('alt_text', models.CharField(help_text='Texto alternativo para accesibilidad', max_length=200)),
                ('seccion', models.CharField(choices=[('mision', 'Misión'), ('vision_valores', 'Visión y Valores')], help_text='Sección donde aparecerá la imagen', max_length=20)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición en el collage')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagen de Collage',
                'verbose_name_plural': 'Imágenes de Collage',
                'ordering': ['seccion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del miembro del equipo', max_length=100)),
                ('puesto', models.CharField(help_text='Puesto o rol en la organización', max_length=100)),
                ('imagen', models.ImageField(help_text='Imagen del miembro del equipo', upload_to='quienes_somos/equipo/')),
                ('frase_destacada', models.TextField(help_text='Frase destacada o cita representativa del miembro')),
                ('email', models.EmailField(blank=True, help_text='Email de contacto (opcional)', max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Perfil de LinkedIn (opcional)', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición en el carrusel')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Miembros del Equipo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Misión', help_text='Título de la sección de misión', max_length=50)),
                ('descripcion', tinymce.models.HTMLField(help_text='Descripción detallada de la misión de la organización')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición en la página')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Misión',
                'verbose_name_plural': 'Misión',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='QuienesSomosConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='Nuestro Propósito', help_text='Título principal de la sección', max_length=100)),
                ('subtitulo_principal', models.CharField(default='Transformar Realidades', help_text='Subtítulo debajo del título principal', max_length=150)),
                ('descripcion_principal', models.CharField(default='A Través De La Educación.', help_text='Descripción que acompaña al subtítulo', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Quiénes Somos',
                'verbose_name_plural': 'Configuración Quiénes Somos',
            },
        ),
        migrations.CreateModel(
            name='SeccionProgramasODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_completo_configurable', models.CharField(default='Nuestros *programas* están *alineados* con el objetivo de desarrollo sostenible de la agenda 20/30 de la *ONU*', help_text='Escribe el título completo. Usa *palabra* para destacar en verde.', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Sección ODS',
                'verbose_name_plural': 'Configuración Sección ODS',
            },
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del valor (ej: Respeto a la persona y su dignidad)', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del valor', null=True)),
                ('icono', models.CharField(blank=True, help_text='Clase de icono (ej: fas fa-heart) - Opcional', max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Valor',
                'verbose_name_plural': 'Valores',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Visión', help_text='Título de la sección de visión', max_length=50)),
                ('descripcion', tinymce.models.HTMLField(help_text='Descripción detallada de la visión de la organización')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=2, help_text='Orden de aparición en la página')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visión',
                'verbose_name_plural': 'Visión',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoDesarrolloSostenible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número del ODS (1-17)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(17)])),
                ('titulo', models.CharField(help_text='Título del objetivo (ej: Educación de Calidad)', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción de cómo el programa se alinea con este objetivo')),
                ('icono', models.ImageField(blank=True, help_text='Icono representativo del ODS (opcional)', null=True, upload_to='quienes_somos/ods_iconos/')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Objetivo de Desarrollo Sostenible',
                'verbose_name_plural': 'Objetivos de Desarrollo Sostenible',
                'ordering': ['orden', 'numero'],
                'unique_together': {('numero',)},
            },
        ),
    ]
