# Generated by Django 5.2.1 on 2025-06-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionprogramasods',
            name='titulo_completo_configurable',
            field=models.CharField(default='Nuestros *programas* están *alineados* con el objetivo de desarrollo sostenible de la agenda 20/30 de la *ONU*', help_text='Escribe el título completo. Usa *palabra* para destacar el texto en verde.', max_length=255),
        ),
    ]
