# Generated by Django 5.2.1 on 2025-06-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_seccionprogramasods_titulo_completo_configurable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivodesarrollosostenible',
            name='icono',
        ),
    ]
