# Generated by Django 5.2.1 on 2025-07-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(default='Av. Juárez #123, Centro Histórico\nCiudad de México, CDMX 06000', verbose_name='Dirección')),
                ('telefono', models.CharField(default='+52 55 1234 5678', max_length=50, verbose_name='Teléfono principal')),
                ('correo', models.EmailField(default='contacto@crecermexico.org', max_length=254, verbose_name='Correo principal')),
                ('horario', models.TextField(default='Lunes a Viernes: 9:00 AM - 6:00 PM\nSábados: 9:00 AM - 2:00 PM', verbose_name='Horario de atención')),
                ('promotora', models.CharField(default='Nadia Pacheco', max_length=100, verbose_name='Promotora')),
                ('tel_promotora', models.CharField(default='5591659457', max_length=20, verbose_name='Tel. promotora')),
                ('promotor', models.CharField(default='Hugo Garrido', max_length=100, verbose_name='Promotor')),
                ('tel_promotor', models.CharField(default='5539688886', max_length=20, verbose_name='Tel. promotor')),
                ('gerente_educativa', models.CharField(default='Paola Quintero Villalvazo', max_length=100, verbose_name='Gerente educativa')),
                ('correo_gerente_educativa', models.EmailField(default='pquintero@crecermexico.org', max_length=254, verbose_name='Correo gerente educativa')),
                ('gerente_operaciones', models.CharField(default='Myriam Saldivar Aguilar', max_length=100, verbose_name='Gerente operaciones')),
                ('correo_gerente_operaciones', models.EmailField(default='msaldivar@crecermexico.org', max_length=254, verbose_name='Correo gerente operaciones')),
                ('correo_servicio_social', models.EmailField(default='amartinez@crecermexico.org', max_length=254, verbose_name='Correo servicio social')),
                ('correo_alianzas', models.EmailField(default='mgallastegui@crecermexico.org', max_length=254, verbose_name='Correo alianzas')),
            ],
            options={
                'verbose_name': 'Información de contacto',
                'verbose_name_plural': 'Información de contacto',
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='sin número', max_length=20),
        ),
    ]
