# Generated by Django 5.2.1 on 2025-07-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactinfo_contactmessage_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='Titulo',
            field=models.TextField(default='Contáctanos', max_length=250, verbose_name='Titulo pagina de Contacto'),
        ),
    ]
