# Generated by Django 5.2.1 on 2025-07-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactinfo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='Subtitulo',
            field=models.TextField(default='Estamos aquí para ayudarte. Envíanos un mensaje y nos pondremos en contacto contigo lo antes posible.', max_length=250, verbose_name='Subtitulo pagina de Contacto'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='Titulo',
            field=models.TextField(default='Contáctanos', max_length=50, verbose_name='Titulo pagina de Contacto'),
        ),
    ]
