# Generated by Django 5.2.1 on 2025-07-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactinfo_subtitulo_alter_contactinfo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='link_ubicacion',
            field=models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3764.131699869895!2d-99.1826777!3d19.3634493!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d1ff8c5eb77755%3A0xe6c846c7ea3e746b!2sCRECER%20M%C3%89XICO!5e0!3m2!1ses!2smx!4v1749783441103!5m2!1ses!2smx', verbose_name='Link de ubicación'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='ubicacion_subtitulo',
            field=models.CharField(default='Visítanos en nuestra oficina principal', max_length=150, verbose_name='Subtitulo Ubicación'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='ubicacion_titulo',
            field=models.CharField(default='Nuestra Ubicación', max_length=100, verbose_name='Titulo Ubicación'),
        ),
    ]
