# Generated by Django 5.2.1 on 2025-07-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactinfo_link_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Mensajes enviados desde Pagina de Contacto', 'verbose_name_plural': 'Mensajes de Contacto'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='Subtitulo',
            field=models.CharField(default='Estamos aquí para ayudarte. Envíanos un mensaje y nos pondremos en contacto contigo lo antes posible.', max_length=250, verbose_name='Subtitulo pagina de Contacto'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='Titulo',
            field=models.CharField(default='Contáctanos', max_length=50, verbose_name='Titulo pagina de Contacto'),
        ),
    ]
