# Generated by Django 5.2.1 on 2025-05-20 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('youtube_id', models.CharField(max_length=20, verbose_name='ID de YouTube')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='home/videos/', verbose_name='Miniatura')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Video destacado',
                'verbose_name_plural': 'Videos destacados',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.TextField(blank=True, verbose_name='Subtítulo')),
                ('card1_icon', models.CharField(max_length=100, verbose_name='Icono tarjeta 1')),
                ('card1_title', models.CharField(max_length=100, verbose_name='Título tarjeta 1')),
                ('card1_description', models.TextField(verbose_name='Descripción tarjeta 1')),
                ('card2_icon', models.CharField(max_length=100, verbose_name='Icono tarjeta 2')),
                ('card2_title', models.CharField(max_length=100, verbose_name='Título tarjeta 2')),
                ('card2_description', models.TextField(verbose_name='Descripción tarjeta 2')),
                ('card3_icon', models.CharField(max_length=100, verbose_name='Icono tarjeta 3')),
                ('card3_title', models.CharField(max_length=100, verbose_name='Título tarjeta 3')),
                ('card3_description', models.TextField(verbose_name='Descripción tarjeta 3')),
                ('primary_button_text', models.CharField(default='Donar', max_length=50, verbose_name='Texto botón primario')),
                ('primary_button_url', models.CharField(default='/donaciones', max_length=255, verbose_name='URL botón primario')),
                ('secondary_button_text', models.CharField(default='Conocer más', max_length=50, verbose_name='Texto botón secundario')),
                ('secondary_button_url', models.CharField(default='/nosotros', max_length=255, verbose_name='URL botón secundario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('section', models.CharField(choices=[('hero', 'Hero'), ('programs', 'Nuestros Programas'), ('testimonial', 'Cita Textual'), ('video', 'Video Destacado')], max_length=20, unique=True, verbose_name='Sección')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título de la sección')),
                ('subtitle', models.TextField(blank=True, verbose_name='Subtítulo de la sección')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Sección de la página de inicio',
                'verbose_name_plural': 'Secciones de la página de inicio',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('image', models.ImageField(upload_to='home/programs/', verbose_name='Imagen')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('button_text', models.CharField(default='Conocer más', max_length=50, verbose_name='Texto del botón')),
                ('url', models.URLField(help_text='Debe incluir http:// o https://', max_length=255, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('site_name', models.CharField(default='Crecer México', max_length=100, verbose_name='Nombre del sitio')),
                ('logo', models.ImageField(upload_to='site/logo/', verbose_name='Logo principal')),
                ('logo_alt', models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='Logo alternativo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/', verbose_name='Favicon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email principal')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('footer_text', models.TextField(blank=True, verbose_name='Texto del pie de página')),
                ('copyright_text', models.CharField(blank=True, max_length=255, verbose_name='Texto de copyright')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta descripción')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta keywords')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='ID de Google Analytics')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuraciones del sitio',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('other', 'Otra')], max_length=50, verbose_name='Red social')),
                ('url', models.URLField(max_length=255, verbose_name='Enlace')),
                ('icon', models.CharField(blank=True, help_text="Clase de icono (ej: 'fab fa-facebook')", max_length=50, verbose_name='Icono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('quote', models.TextField(verbose_name='Cita')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/testimonials/', verbose_name='Imagen')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-is_featured', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HeroCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/hero_carousel/', verbose_name='Imagen')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='0 = primera, 1 = segunda, …', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='core.hero', verbose_name='Hero')),
            ],
            options={
                'verbose_name': 'Imagen del Hero',
                'verbose_name_plural': 'Imágenes del Hero',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('location', models.CharField(choices=[('header', 'Menú principal'), ('footer', 'Pie de página'), ('both', 'Ambos')], default='header', max_length=20, verbose_name='Ubicación')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='Elemento padre')),
            ],
            options={
                'verbose_name': 'Elemento del menú',
                'verbose_name_plural': 'Elementos del menú',
                'ordering': ['location', 'order'],
            },
        ),
    ]
