# Generated by Django 5.2.1 on 2025-05-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herocarouselimage',
            options={'ordering': ['order'], 'verbose_name': 'Imagen del Carrusel del Hero', 'verbose_name_plural': 'Imágenes del Carrusel del Hero'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='home/testimonials/', verbose_name='Imagen de perfil'),
        ),
    ]
