# Generated by Django 5.2.1 on 2025-05-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_herocarouselimage_options_testimonial_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='footer_text',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text_col1',
            field=models.TextField(blank=True, verbose_name='Texto pie de página (Columna 2)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text_col2',
            field=models.TextField(blank=True, verbose_name='Texto pie de página (Columna 2)'),
        ),
        migrations.AlterField(
            model_name='featuredvideo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/testimonials/', verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='home/testimonials/', verbose_name='Imagen'),
        ),
    ]
