# Generated by Django 5.2.1 on 2025-06-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_siteconfiguration_footer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_text_col1',
            field=models.TextField(blank=True, verbose_name='Texto pie de página (Columna 1)'),
        ),
    ]
