# Generated by Django 5.2.1 on 2025-07-08 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(help_text='Logo del aliado (recomendado: formato PNG con fondo transparente)', upload_to='aliados/')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición en la página')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aliado',
                'verbose_name_plural': 'Aliados',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAliados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nuestros Aliados', max_length=200)),
                ('subtitulo', models.TextField(blank=True, help_text='Subtítulo opcional para la sección de aliados')),
            ],
            options={
                'verbose_name': 'Configuración de Aliados',
                'verbose_name_plural': 'Configuración de Aliados',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaPorEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aguascalientes', 'Aguascalientes'), ('baja_california', 'Baja California'), ('baja_california_sur', 'Baja California Sur'), ('campeche', 'Campeche'), ('chiapas', 'Chiapas'), ('chihuahua', 'Chihuahua'), ('coahuila', 'Coahuila'), ('colima', 'Colima'), ('durango', 'Durango'), ('guanajuato', 'Guanajuato'), ('guerrero', 'Guerrero'), ('hidalgo', 'Hidalgo'), ('jalisco', 'Jalisco'), ('mexico', 'Estado de México'), ('michoacan', 'Michoacán'), ('morelos', 'Morelos'), ('nayarit', 'Nayarit'), ('nuevo_leon', 'Nuevo León'), ('oaxaca', 'Oaxaca'), ('puebla', 'Puebla'), ('queretaro', 'Querétaro'), ('quintana_roo', 'Quintana Roo'), ('san_luis_potosi', 'San Luis Potosí'), ('sinaloa', 'Sinaloa'), ('sonora', 'Sonora'), ('tabasco', 'Tabasco'), ('tamaulipas', 'Tamaulipas'), ('tlaxcala', 'Tlaxcala'), ('veracruz', 'Veracruz'), ('yucatan', 'Yucatán'), ('zacatecas', 'Zacatecas'), ('cdmx', 'Ciudad de México')], max_length=50, unique=True)),
                ('total_egresados', models.PositiveIntegerField(default=0)),
                ('egresados_hombres', models.PositiveIntegerField(default=0)),
                ('egresados_mujeres', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estadística por Estado',
                'verbose_name_plural': 'Estadísticas por Estado',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticasImpacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nuestro Impacto en México', max_length=200)),
                ('subtitulo', models.TextField(default='Conoce el alcance de nuestro programa educativo a nivel nacional')),
            ],
            options={
                'verbose_name': 'Estadísticas de Impacto',
                'verbose_name_plural': 'Estadísticas de Impacto',
            },
        ),
        migrations.CreateModel(
            name='InformeAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Informe Anual', max_length=200)),
                ('subtitulo', models.TextField(default='Conoce los resultados de nuestro trabajo durante el año')),
                ('año', models.PositiveIntegerField(default=2024)),
                ('archivo_pdf', models.FileField(help_text='Archivo PDF del informe anual', upload_to='informes_anuales/')),
                ('imagen_portada', models.ImageField(help_text='Imagen de portada del informe', upload_to='informes_anuales/portadas/')),
                ('texto_boton', models.CharField(default='LEER INFORME', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateField()),
            ],
            options={
                'verbose_name': 'Informe Anual',
                'verbose_name_plural': 'Informes Anuales',
                'ordering': ['-año'],
            },
        ),
        migrations.CreateModel(
            name='MetricasImpacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incremento_ingresos', models.PositiveIntegerField(default=42, help_text='Porcentaje de egresados que incrementaron sus ingresos', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recibio_ascenso', models.PositiveIntegerField(default=26, help_text='Porcentaje de egresados que recibieron un ascenso', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('emprendi_negocio', models.PositiveIntegerField(default=25, help_text='Porcentaje de egresados que emprendieron un negocio', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('continuo_estudios', models.PositiveIntegerField(default=23, help_text='Porcentaje de egresados que continuaron estudios de media superior', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('formacion_continua', models.PositiveIntegerField(default=11, help_text='Porcentaje de egresados que se inscribieron a cursos de formación continua', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métricas de Impacto',
                'verbose_name_plural': 'Métricas de Impacto',
            },
        ),
        migrations.CreateModel(
            name='TestimonioEgresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Historias de Éxito', max_length=200)),
                ('video_youtube_id', models.CharField(help_text='ID del video de YouTube (ejemplo: dQw4w9WgXcQ)', max_length=100)),
                ('texto_testimonial', models.TextField(help_text='Texto que acompaña al video testimonial')),
                ('nombre_egresado', models.CharField(max_length=100)),
                ('programa_completado', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonio de Egresado',
                'verbose_name_plural': 'Testimonios de Egresados',
            },
        ),
    ]
