# Generated by Django 5.2.1 on 2025-07-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='impact/carousel/', verbose_name='Imagen')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='0 = primera, 1 = segunda, …', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Imagen del Carrusel',
                'verbose_name_plural': 'Imágenes del Carrusel',
                'ordering': ['order'],
            },
        ),
    ]
