# Generated by Django 5.2.1 on 2025-07-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0002_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(default='', help_text='Título de la imagen del carrusel', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
