# Generated by Django 5.2.1 on 2025-07-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0003_carouselimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(blank=True, help_text='Se genera automáticamente desde el nombre del archivo', max_length=200, verbose_name='Título'),
        ),
    ]
